-- Run this once in the Supabase SQL editor (Project → SQL Editor → New query).
-- National mairies campaign (scripts/prepare_mairies_chloe.py → dashboard import):
-- 1. Send order: Chloé takes pending prospects in import order, and the CSV is
--    already sorted North → South, so the queue follows the map.
-- 2. contacted_at: date of the first email, shown in the "Prospects" tab.
-- 3. Case-insensitive unique email: two rows for one address are impossible.
-- 4. Batch lock + 90 emails/day for Chloé.
-- 5. Switch for the automatic sends (dashboard button « Envois automatiques »).

-- ── 1. Queue position ───────────────────────────────────────────────────────────
-- Identity values are handed out in insert order (one CSV import = one insert,
-- rows in file order). Existing rows get numbers too, so the older backlog
-- stays ahead of the national file.
alter table prospects add column if not exists queue_pos bigint generated by default as identity;
create index if not exists idx_prospects_queue on prospects(status, queue_pos);

-- ── 2. Date of first contact ────────────────────────────────────────────────────
alter table prospects add column if not exists contacted_at timestamptz;
update prospects p set contacted_at = s.first_sent
from (
  select prospect_id, min(sent_at) as first_sent from outreach_emails
  where status = 'sent' and sequence_step = 0 group by prospect_id
) s
where s.prospect_id = p.id and p.contacted_at is null;
create index if not exists idx_prospects_contacted_at on prospects(contacted_at desc);

-- ── 3. One row per address, whatever the case ──────────────────────────────────
update prospects set email = lower(trim(email))
where email <> lower(trim(email))
  and not exists (select 1 from prospects q where q.email = lower(trim(prospects.email)));

do $$
begin
  if exists (select 1 from prospects group by lower(email) having count(*) > 1) then
    raise notice 'Adresses en double (casse) dans prospects : index non créé. Liste : %',
      (select string_agg(e, ', ') from (select lower(email) e from prospects group by 1 having count(*) > 1) d);
  else
    create unique index if not exists uniq_prospects_email_lower on prospects (lower(email));
  end if;
end $$;

alter table outreach_emails add column if not exists recipient_email text;
create index if not exists idx_outreach_recipient on outreach_emails (lower(recipient_email));
create index if not exists idx_roof_leads_contact_email on roof_leads (lower(contact_email));

-- ── 4. Chloé: one batch at a time, 90 emails per day ────────────────────────────
alter table agents add column if not exists batch_lock_until timestamptz;
update agents set config = config || '{"daily_limit": 90}'::jsonb where slug = 'chloe';

-- ── 5. Automatic sends on/off ───────────────────────────────────────────────────
-- Off = the morning crons (Chloé's batch, Hugo's relances) do nothing; the
-- "Envoyer le prochain lot" button keeps working, so Nordine stays in charge.
alter table settings add column if not exists auto_send boolean not null default true;
